* [Broadcasting](#Broadcasting)
* [Flatten](#Flatten)
* [Ravel()](#Ravel())
* [Transpose()](#Transpose())
* [Swapaxes()](#Swapaxes())
* [<font color='red'>Concatenate()</font>](#Concatenate())

### START
***

In [22]:
import numpy as np

#help(np.array)

In [2]:
np.array((3, 3, 3, 3), ndmin = 2)

array([[3, 3, 3, 3]])

In [3]:
np.array(([1, 2], [3, 4]), order = "c")

array([[1, 2],
       [3, 4]])

In [4]:
np.arange((4), (4))

array([], dtype=int32)

In [5]:
np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [23]:
#help(np.zeros)

In [7]:
np.empty(3)

array([1.39512741e-311, 0.00000000e+000, 6.47591605e-319])

In [8]:
a.empty

NameError: name 'a' is not defined

In [ ]:
help(np.linspace)

In [ ]:
np.linspace(2, 3, 10, endpoint = False)

In [24]:
#help(np.eye)

In [14]:
np.eye(3, k = -1, dtype = int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
print(a[1][2])

7


In [25]:
#help(np.identity)

In [20]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
#help(np.random)

In [27]:
#help(np.random.rand)

In [29]:
import numpy.random as np

np.rand(2, 3)

array([[0.03526856, 0.83174658, 0.77336723],
       [0.01716241, 0.78768927, 0.03960206]])

In [28]:
#help(np.randn)

In [31]:
np.randn(2, 3)

array([[-0.32398253, -0.26071365, -0.94114329],
       [-0.83792121,  0.26854281, -0.20386987]])

In [33]:
np.rand(2, 3)

array([[-0.22905888, -0.62151275, -0.01247402],
       [-0.41223248, -0.85800036, -0.21138049]])

In [41]:
np.ranf((2, 2)) 

array([[0.29158007, 0.33012756],
       [0.43764148, 0.51747478]])

In [48]:
np.randint(1, 100, (3, 3))

array([[92, 81, 51],
       [25, 97, 72],
       [79,  3, 13]])

In [51]:
a.ndim

2

In [16]:
import numpy as np

b = np.array([[1, 2, 3], [1, 2, 3]])
b.ndim
b.shape
b.itemsize

4

In [17]:
np.zeros((2, 2, 2)).itemsize

8

In [18]:
a = np.array([1, 2, 3, 4, 5])
a[1]

2

# Array indexing (Advanced)

In [1]:
import numpy as np

a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
i = np.array([2, 4, 6])
a[i]

array([3, 5, 7])

In [28]:
b = np.array([[1, 2], [4, 5]])


# Boolean Indexing

In [13]:
c = np.array([1, 2, -1])

In [16]:
c[c < 0]

array([-1])

In [17]:
c * i

array([ 2,  8, -6])

In [29]:
c = np.array([[1, 2], [1, 2]])
c * b

array([[ 1,  4],
       [ 4, 10]])

# Matrix Multiplication


In [30]:
b

array([[1, 2],
       [4, 5]])

In [31]:
c

array([[1, 2],
       [1, 2]])

In [32]:
b.dot(c)

array([[ 3,  6],
       [ 9, 18]])

In [33]:
c.dot(b)

array([[ 9, 12],
       [ 9, 12]])

# Broadcasting


In [40]:
a = np.array([1, 2]) # from right atleast both sizes must be equal or atleast one size must be "one"
a + b

array([[2, 4],
       [5, 7]])

In [42]:
a = np.array([[1], [2]])
a

array([[1],
       [2]])

In [43]:
a + b

array([[2, 3],
       [6, 7]])

In [44]:
w = np.array([1, 2])
a + w

array([[2, 3],
       [3, 4]])

# Array manipulation
   ***
   ### Reshape
   

In [1]:
import numpy as np

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.reshape(a, (2, 5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b.shape

(2, 5)

In [5]:
a.shape

(10,)

In [11]:
b = np.reshape(a, (2, 5), "F")        #F = store values column wise, C = store values row wise.
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [12]:
b.size

10

In [16]:
b = np.array(a).reshape(-1, 1) 
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### Resize
***

In [20]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.resize(a, (2, 10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Flatten
*Flatten is a method.*
***

In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
a.flatten("F")

array([1, 5, 2, 6, 3, 7, 4, 8])

In [33]:
a.flatten("C")

array([1, 2, 3, 4, 5, 6, 7, 8])

### Ravel()
*Ravel is a function*
***

In [34]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
np.ravel(a, "F")

array([1, 5, 2, 6, 3, 7, 4, 8])

In [37]:
a.ravel("F")

array([1, 5, 2, 6, 3, 7, 4, 8])

### Transpose()
***

In [1]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
np.transpose(a)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [2]:
a = np.transpose(a, (0, 1))      #(o, 1)==> same as input, (1, 0)==>reversed

In [3]:
np.transpose(a, (0, 1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Swapaxes()
***

In [5]:
np.swapaxes(a, 1, 0)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Concatenate()
***

In [13]:
a = np.arange(5)     #If axis is none it will flatten and concatenate, out is the output array name
b = np.arange(5)
c = np.arange(5)
np.concatenate((a, b, c), 0)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [17]:
d = np.zeros(15, dtype = int)

In [18]:
np.concatenate((a, b, c), out = d)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [25]:
e = np.array([[1, 2], [3, 4]])
f = np.array([[5, 6], [7, 8]])
np.concatenate((e, f))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.concatenate((e.flatten(), f.flatten()))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
1,2 



[START](#START)