In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
a - 2

array([-1,  0,  1,  2])

# Simply


In [13]:
a = np.ones(3, dtype= int)
b = a - 2
print(b)

[-1 -1 -1]


In [16]:
c = a - b

In [18]:
m = 2
c = np.arange(1, 5)
m ** c 

array([ 2,  4,  8, 16], dtype=int32)

# simply
- simply

In [31]:
d = np.ones((3, 3), dtype= int)
f = d .dot(d)

In [32]:
e = np.ones((3, 3), dtype = int)
f == e

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [35]:
f > e

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [36]:
f != e

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
np.array_equal(f, e)

False

In [38]:
np.logical_and(f, e)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
g = np.zeros((3, 3))
np.logical_and(g, e)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [40]:
np.logical_not(g)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [45]:
np.exp(np.array([1, 2, 3]))

array([ 2.71828183,  7.3890561 , 20.08553692])