In [11]:
import numpy as np

a = np.array([2, 1, 70])


In [12]:
a.argsort(axis = 0)

array([1, 0, 2], dtype=int64)

In [21]:
b = np.tile(np.array([1, 2, 3, 4]), (3, 1))
print(b)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [22]:
b.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [24]:
c = np.array([5, 6, 7, 8])
print(c)
b + c

[5 6 7 8]


array([[ 6,  8, 10, 12],
       [ 6,  8, 10, 12],
       [ 6,  8, 10, 12]])